name: Deploy to Prod

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="$(date +%Y%m%d%H%M%S)"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKER_USERNAME }}/profanity-filter:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/profanity-filter:$IMAGE_TAG

      - name: Update image tag in k8s overlay
        run: |
          sed -i "s|tag: \".*\"|tag: \"$IMAGE_TAG\"|" k8s/overlays/prod/values.yaml

      - name: Commit and push updated k8s config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/overlays/prod/values.yaml
          git commit -m "ci(prod): update image tag to $IMAGE_TAG"
          git push origin master